### ISSUE TITLE
scikit-survival converters

### ISSUE THREAD

**Issue by ealonso-vicomtech** [onnx/sklearn-onnx#1065]
Hi,

I've been looking for how to convert [scikit-survival](https://scikit-survival.readthedocs.io/en/stable/index.html) models but haven't found anything. 

Is there a possibility that you implement such converters? Or would it be too complicated to implement it myself?

**Comment by sdpython** [comment]
We don't plan to do it in that package since it is specific to scikit-learn. It could be done as an extension. It is not necessary complicated but it takes time to make the sure the conversion produces an accurate onnx model. Maybe we could create a very light project with a model as a starter but we would need contributors to write converters.

**Comment by xadupre** [comment]
For the next step, I suggest you pick a model you need to convert in scikit-survival (if possible a simple one). Then maybe you can create a repository set up the way you like or I can do it. I would then submit a PR with an first converter. How does it sound?

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.
