### ISSUE TITLE
Dictionary with mixed types for key or value?

### ISSUE THREAD

**Issue by calebmadrigal** [onnx/sklearn-onnx#107]
I was trying to convert a sklearn Pipeline+FeatureVectorizer model which takes as input a dictionary of this form: `{ 0: <float>, 1: <float>, 2: <float>, 3: <float>, 'city': <string> }`. But when I looked at the [`DictionaryType`](https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/common/data_types.py#L134) definition, it appears that there can only be one key type and one value type (in other words, all the keys in an input dictionary must be the same type, and all the values in an input dictionary must be the same type).

Are there any plans to support mixed types for dictionary keys/values? Supporting mixed types like this could help people take advantage of the sklearn feature engineering transformers better, but I don't know the ONNX limitations or the complexities of adding support for this. Or is this supported in some way I missed?

Thanks!

**Comment by prabhat00155** [comment]
Are you using a DictVectorizer? I don't think DictVectorizer supports having different key types either:

from sklearn.feature_extraction import DictVectorizer

dict1 = [
    {0: -0.3, 1: 3.1, 2: 2.1, 3: 5.6, 'city': 'London'},
    {0: 1.3, 1: 3.1, 2: 2.1, 3: 5.6, 'city': 'Paris'},
]
DictVectorizer(sparse=False).fit_transform(dict1)

TypeError: '<' not supported between instances of 'str' and 'int'

You could, however, make all the keys as string and have different types of values. For example:
dict1 = [
    {'0': -0.3, '1': 3.1, '2': 2.1, '3': 5.6, 'city': 'London'},
    {'0': 1.3, '1': 3.1, '2': 2.1, '3': 5.6, 'city': 'Paris'},
]

This should work with Scikit, but currently doesn't work with sklearn-onnx as DictionaryType expects a single value type. Perhaps, this could be fixed by accepting a list of value types in DictionaryType. I'll look into this. Thanks for reporting the issue.

**Comment by calebmadrigal** [comment]
@prabhat00155 Yep, I am using a `DictVectorizer`. Good call on the keys needing to be the same. But yes, I believe the value types should be mixable.

**Comment by xadupre** [comment]
Many runtimes are implemented in C or C++ and having mixable type for the values is not supported. I would suggest to convert the whole column into strings before fitting it.
