### ISSUE TITLE
How can I pipe custom operations to a standard sklearn operations? 

### ISSUE THREAD

**Issue by alexandreCameron** [onnx/sklearn-onnx#278]
Hi,

I'm really impressed by the achievements of the package, especially by the easy conversion of sklearn pipelines to onnx. 

However, I'm requiring a little more flexibility in my project. I'll like to use a custom operation before applying an sklearn operation, for example: 
1. operation 1 : X_1 = log(X_0) : it could be `sklearn.preprocessing.FunctionTransformer(func=np.log, inverse_func=np.exp)` or `skl2onnx.algebra.onnx_ops.OnnxLog` 
2. operation 2 : X_2 = `sklearn.preprocessing.StandardScaler.fit_transform`(X_1) 

But the `convert_sklearn` of `FunctionTransformer` is not implemented and I haven't been able to pipe properly `onnx_ops` to other transformations. 

What is the best way to create a skl2onnx graph with custom transformation? 

Will you implement `FunctionTransformer` in the near future?

**Comment by prabhat00155** [comment]
I think what you need is to add a Log node which processes the input, this would be followed by StandardScaler. 
@xadupre: Do you know how to add a custom node to the graph?

**Comment by xadupre** [comment]
FunctionTransformer is tricky because the function to convert may be impossible to convert into ONNX. Assuming you want to use existing onnx nodes (so with a dedicated runtime), it requires to convert python code into ONNX. I started to look into that direction (http://www.xavierdupre.fr/app/mlprodict/helpsphinx/i_ex.html#index-exref-0-4) but the coverage of numpy functions it supports is small.

The best option now is to create your own transformer, to implement the corresponding converter, to register it so that skl2onnx can pick it up. The only example I wrote is the following https://github.com/onnx/sklearn-onnx/blob/master/docs/examples/plot_custom_model.py but that's not the easiest one.

**Comment by mnp** [comment]
So we've met this issue doing exactly what OP above is doing.  I'm investigating the two approaches above, but also encountered [this post](https://stackoverflow.com/questions/39406539/sklearn-function-transformer-in-pipeline) suggesting `sklearn-pandas.DataFrameMapper` might be an option.  Forgive me if it's far from the mark here, but does anyone have an opinion about that approach and how it compares to the other two?  Thanks!

**Comment by xadupre** [comment]
This example will be soon part of the documentation: https://github.com/xadupre/sklearn-onnx/blob/tuto/docs/tutorial/plot_icustom_converter.py. It is an end to end example which creates a custom transformer and its own converter.
