### ISSUE TITLE
SVC decision function support

### ISSUE THREAD

**Issue by konabuta** [onnx/sklearn-onnx#302]
Is there any roadmap to support output of[ decision_function](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.decision_function) of SVC  ? or Any workaround ?

Regards,
Keita

**Comment by prabhat00155** [comment]
@xadupre Don't we return the result of decision_function in SVC if probability=False?

**Comment by xadupre** [comment]
Currently no. Some explanations are in the documentation of the converter: https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/support_vector_machines.py#L17. scikit-learn had different raw scores than svmlib. There was a change in SVC scores in scikit-learn after I wrote this converter. It should be revisited.

**Comment by xadupre** [comment]
I implemented the converter because the following issue was fixed: https://github.com/scikit-learn/scikit-learn/issues/13030 fixed in PR https://github.com/scikit-learn/scikit-learn/pull/10440. I think it is now available in 0.21. Unfortunately, there is no easy way of fixing it in onnx. We either need to implement function _ovr_decision_function in ONNX or create an new operator.

**Comment by xadupre** [comment]
Fixes in #451.

**Comment by 0101101001001100** [comment]
Hello, I am trying to convert an SVC to ONNX with `skl2onnx-1.9.1` with raw scores, but it seems like it is not allowed. Is it possible to work around this limitation?

> NameError: Option 'raw_scores' not in ['nocl', 'zipmap'] for class 'SVC'.
