### ISSUE TITLE
Segmentation fault when imported after torch 

### ISSUE THREAD

**Issue by arsenyinfo** [onnx/sklearn-onnx#511]
`Segmentation fault (core dumped)` happens when `skl2onnx` is imported after `torch`. 

Can be reproduced on Ubuntu 16.04 with Python 3.5.8, torch<1.5.0 (happens with 1.2.0, 1.3.0, 1.4.0) and skl2onnx==1.7.0 with a tiny command `python -c "import torch; import skl2onnx"`

**Comment by xadupre** [comment]
Did you try something like ``import torch; import onnx``. skl2onnx does not have C++ code in it, I suppose the conflict happens with one of its dependencies (onnx, onnxruntime, scikit-learn).

**Comment by arsenyinfo** [comment]
@xadupre `import torch; import {onnx, onnxruntime, scikit-learn}` work fine. 

When python is run with `-v`, it explodes here: 
```
# code object from '/vision/.env/lib/python3.5/site-packages/skl2onnx/algebra/__pycache__/automation.cpython-35.pyc'
import 'skl2onnx.algebra.automation' # <_frozen_importlib_external.SourceFileLoader object at 0x7fd7580781d0>
Segmentation fault
```

**Comment by xadupre** [comment]
My understanding is pytorch has conflict when sklearn-onnx dynamically creates classes. If the problem is fixed for the latest version of pytorch, I'm reluctant to investigate. I'm not sure the fix can be handled on sklearn-onnx's side. It may be a jit optimization torch performs which crashes but that's all I can say about it. Is there anyway you can use more recent versions?

**Comment by arsenyinfo** [comment]
Unfortunately, I can't update torch version for a while; for now, I wrapped my torch imports so it always imports `skl2onnx` before. It's ugly, but it works :)

**Comment by xadupre** [comment]
May I close the issue?

**Comment by arsenyinfo** [comment]
@xadupre Please feel free!
