### ISSUE TITLE
DBSCAN converter not implemented

### ISSUE THREAD

**Issue by al-rigazzi** [onnx/sklearn-onnx#739]
It would be nice to have a DBSCAN converter, as it would add a clustering algorithm with the capability of finding outliers.

**Comment by xadupre** [comment]
DBSCAN is a model which does have any transform or predict method. That's why it has no converter. Adding one would mean to implement the training algorithm, including this function [dbscan_inner](https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/cluster/_dbscan_inner.pyx#L21), with onnx operators. The best option would be to have a dedicated operator for that. Which runtime do you plan to use for once it is converted?

**Comment by al-rigazzi** [comment]
Hi, @xadupre, thanks for the reply!

It is true there is no `predict` for `DBSCAN`, but there is a `fit_predict` method. I thought that `KMeans` had been ported in a similar way, but I see there is a pure `predict` method for it, so maybe I was wrong.

Regarding the second part of your question, my idea would be to use DBSCAN inside RedisAI, where the ONNX runtime is supported.

**Comment by xadupre** [comment]
All converter implements transform or predict methods with ONNX operators. There is no training right now. The training algorithm is implemented here: https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/cluster/_dbscan_inner.pyx and that's not easy to implement with ONNX. An option such as implementing a python runtime for this specific operator and register to onnxruntime with this extension: https://github.com/microsoft/onnxruntime-extensions. Or even implement it in C++.

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.
