### ISSUE TITLE
Revert onnx model to original format (scikit learn, tf...)

### ISSUE THREAD

**Issue by lherbeur** [onnx/sklearn-onnx#866]
Hi there, 
I was looking to through the APIs for sklearn-onnx for the conversion of an onnx model but it seems that's not currently supported. Is there a way to do this and if not, can this be considered for an enhancement? 
Similar request for tf reverse conversion - https://github.com/onnx/onnx-tensorflow/issues/489. 
Thanks.

**Comment by xadupre** [comment]
Reverr onnx model is easier with tensorflow because you can express most of the onnx operator with tensorfoow functions. With scikit-learn, we could translate the onnx graph into a python code using numpy to compute the output. But i guess that's not what you meant. Onnx introduced functions. We could probably use one function for every model in a pipeline and let the main onnx graph call them as scikit-learn does in a pipeline. But that would require a significant code change.

**Comment by lherbeur** [comment]
Hey, 
The second option sounds more like what I would love, where the model can be reverted and called with scikit learn functions or at least, the equivalent of such functions and attributes.

**Comment by xadupre** [comment]
I started to look into that here: [Use function when converting into ONNX](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/onnx_sklearn_functions.html). Every piece of a pipeline is exported as a function. It stores the hyperparameters as well. It is possible to build a scikit-learn pipeline equivalent to the original model but getting the same pipeline filled with the coefficients stored into the ONNX model means implementing a converter from ONNX to scikit-learn for every model in scikit-learn.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
